---
- name: Setup Web Terminal (Wetty) and NGINX
  hosts: all
  become: yes
  vars:
    wetty_port: 3000
    ssh_host: "{{ ansible_default_ipv4.address }}"
    nginx_config_file: "/etc/nginx/sites-available/default"
    minio_password: "{{ vault_minio_password }}"
  tasks:
    - name: Ensure NGINX is installed
      package:
        name: nginx
        state: present

    - name: Copy Terminal systemd service file
      template:
        src: terminal.service.j2
        dest: /etc/systemd/system/terminal.service
        force: yes
      notify:
        - "Reload systemd"
        - "Restart terminal service"

    - name: Ensure Docker image is pulled
      docker_image:
        name: wettyoss/wetty
        tag: latest
        source: pull

    - name: Enable and start the Terminal service
      systemd:
        name: terminal
        state: started
        enabled: yes

    - name: Set password for minio user
      user:
        name: minio
        password: "{{ minio_password | password_hash('sha512') }}"
        update_password: always

    - name: Configure NGINX for Terminal
      blockinfile:
        path: "{{ nginx_config_file }}"
        insertafter: "^ *server_name {{ inventory_hostname }}; # managed by Certbot.*$"
        block: |
          location ^~ /terminal {
            proxy_pass http://127.0.0.1:{{ wetty_port }}/terminal;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 43200000;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
          }
      notify:
        - "Restart terminal service"
        - "Reload NGINX"

  handlers:
    - name: "Reload systemd"
      systemd:
        daemon_reload: yes

    - name: "Restart terminal service"
      systemd:
        name: terminal
        state: restarted
        enabled: yes

    - name: "Reload NGINX"
      systemd:
        name: nginx
        state: reloaded
