FROM pandoc/extra:latest-ubuntu

RUN apt-get update && apt-get install -y fonts-dejavu fonts-inter
RUN mkdir -p /opt/minio/images
COPY minio-logo.png /opt/minio/images/
COPY eisvogel-minio.latex /.pandoc/templates/
