# four node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "127.0.0.1"
    protocol: TCP
  extraMounts:
  - hostPath: /Users/pavel/disk-control-plane
    containerPath: /disk
    propagation: HostToContainer
- role: worker
  extraPortMappings:
  - containerPort: 30081
    hostPort: 30081
    listenAddress: "127.0.0.1"
    protocol: TCP
  extraMounts:
  - hostPath: /Users/pavel/disk-worker1
    containerPath: /disk
    propagation: HostToContainer
- role: worker
  extraPortMappings:
  - containerPort: 30082
    hostPort: 30082
    listenAddress: "127.0.0.1"
    protocol: TCP
  extraMounts:
  - hostPath: /Users/pavel/disk-worker2
    containerPath: /disk
    propagation: HostToContainer
- role: worker
  extraPortMappings:
  - containerPort: 30083
    hostPort: 30083
    listenAddress: "127.0.0.1"
    protocol: TCP
  extraMounts:
  - hostPath: /Users/pavel/disk-worker3
    containerPath: /disk
    propagation: HostToContainer
- role: worker
  extraPortMappings:
  - containerPort: 30084
    hostPort: 30084
    listenAddress: "127.0.0.1"
    protocol: TCP
  extraMounts:
  - hostPath: /Users/pavel/disk-worker4
    containerPath: /disk
    propagation: HostToContainer
